name: Production Canary Deployment

on:
    push:
        branches:
            - dev
            - feature-1
    pull_request:
        branches:
            - main

#     push:
#         branches:
#             - dev
#             - feature-1
#     pull_request:
#         branches:
#             - main

env:
    GCLOUD_PROJECT: ${{ secrets.PROJECT_ID }}


jobs:
  deploy-canary:
    name: "Phase 1: 10% Canary"
    runs-on: self-hosted
    environment: canary-testing # Manual Gate 1
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/428421184142/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'github-runner-sa@gcp-test-1618-dev.iam.gserviceaccount.com'
          project_id: gcp-test-1618-dev

      - name: Get GKE Credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'gke-dev'
          location: 'us-central1-a'
          project_id: gcp-test-1618-dev
          use_internal_ip: true

      - name: Check/Install NGINX
        run: |
          if ! kubectl get ns ingress-nginx > /dev/null 2>&1; then
            kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml
            sleep 30 # Give GCP time to start the LB
          fi

      - name: Deploy Canary (10%)
        run: |
          # 1. Base Apps & Main Ingress (V1)
          kubectl apply -f k8s/app-v1.yaml
          kubectl apply -f k8s/nginx-main-ingress.yaml
          
          # 2. Canary App & Canary Ingress (V2 @ 10%)
          kubectl apply -f k8s/app-v2.yaml
          kubectl apply -f k8s/nginx-canary-ingress.yaml

  promote-to-prod:
    name: "Phase 2: 100% Rollout"
    needs: deploy-canary
    runs-on: self-hosted
    environment: production-live # Manual Gate 2
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/428421184142/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'github-runner-sa@${{ env.GCLOUD_PROJECT }}.iam.gserviceaccount.com'
          project_id: ${{ env.GCLOUD_PROJECT }}

      - name: Get GKE Credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'gke-dev'
          location: 'us-central1-a'
          project_id: ${{ env.GCLOUD_PROJECT }}
          use_internal_ip: true

      - name: Promote V2 to 100%
        run: |
          # 1. Update Main Ingress to point to V2 service
          kubectl apply -f k8s/nginx-main-ingress-v2.yaml
          
          # 2. Cleanup Canary Rule
          kubectl delete -f k8s/nginx-canary-ingress.yaml


# name: Production Canary Deployment

# on:
#   push:
#     branches: [ main ]

# jobs:
#   # PHASE 1: Deploy Canary (10% Traffic)
#   deploy-canary:
#     name: "Deploy 10% Canary"
#     runs-on: self-hosted
#     environment: canary-testing # GATE 1: Manual Approval
#     permissions:
#       contents: read
#       id-token: write

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Authenticate to GCP
#         uses: 'google-github-actions/auth@v2'
#         with:
          # workload_identity_provider: 'projects/428421184142/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          # service_account: 'github-runner-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com'

#       - name: Get GKE Credentials
#         uses: 'google-github-actions/get-gke-credentials@v2'
#         with:
#           cluster_name: 'your-cluster-name'
#           location: 'your-region'

#       - name: Apply Canary Resources
#         run: |
#           # 1. Ensure v1 is running as the base
#           kubectl apply -f k8s/app-v1.yaml
#           kubectl apply -f k8s/nginx-main-ingress.yaml
          
#           # 2. Deploy v2 Pods
#           kubectl apply -f k8s/app-v2.yaml
          
#           # 3. Inject 10% traffic split via Canary Ingress
#           kubectl apply -f k8s/nginx-canary-ingress.yaml
          
#           echo "Canary phase active: 10% traffic to v2."

#   # PHASE 2: Promote to 100% (Manual Verification)
#   promote-to-production:
#     name: "Promote to 100% Production"
#     needs: deploy-canary
#     runs-on: self-hosted
#     environment: production-live # GATE 2: Manual Approval after stability check
#     permissions:
#       contents: read
#       id-token: write

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Authenticate to GCP
#         uses: 'google-github-actions/auth@v2'
#         with:
#           workload_identity_provider: 'projects/428421184142/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
#           service_account: 'github-runner-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com'

#       - name: Get GKE Credentials
#         uses: 'google-github-actions/get-gke-credentials@v2'
#         with:
#           cluster_name: 'your-cluster-name'
#           location: 'your-region'

#       - name: Shift 100% Traffic to V2
#         run: |
#           # 1. Update the Main Ingress to point to v2 service
#           kubectl apply -f k8s/nginx-main-ingress-v2.yaml
          
#           # 2. Delete the Canary Ingress (Cleanup)
#           kubectl delete -f k8s/nginx-canary-ingress.yaml
          
#           # 3. Scale down v1 (Optional: keeping it for 5 mins for rollback safety)
#           echo "Promotion Complete: 100% traffic on v2."